import Head from "next/head";
import React from "react";
import styled from "styled-components";

type Props = {
  children: JSX.Element;
  title: string;
};

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  padding: 20px;
  align-items: center;
  justify-content: center;
`;

const PageLayout: React.FC<Props> = ({ children, title }) => {
  return (
    <Wrapper>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </Wrapper>
  );
};

export default PageLayout;
