import type { NextPage } from "next";
import Head from "next/head";

import Github from "../components/Cards/Github";
import Lastfm from "../components/Cards/Lastfm";

import HeroParagraph from "../components/Hero/HeroParagraph";
import HeroSection from "../components/Hero/HeroSection";
import HeroLinks from "../components/Hero/HeroLinks";



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ted2xmen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection title="Tuğrul Erdem Dogru" />
      <HeroParagraph />
      <HeroLinks />
      <Lastfm />
      <Github />
    </>
  );
};

export default Home;
