import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Button from "../components/Button";
import ListItem from "../components/ListItem";
import Badges from "../components/Badges";

const Wrapper = styled.div`
  color: green;
  padding: 10px;
  margin: 10px;
`;

const Layout = styled.div`
  display: flex;
  justify-content: center;
  padding: 30px;
`;

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App s</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Wrapper>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Wrapper>
        <Button size="lg" variant="primary">
          Primary LG
        </Button>
        <Button rounded size="sm" variant="secondary">
          Secondary SM -rounded
        </Button>
        <ul>
          <ListItem
            src="https://yt3.ggpht.com/tLOaVyDRQq46qga99PFlP9b3PRcni8gBJepNOecsgIdADpxU10p6w0VD-fZ8VvtqeldN6IHYOj0=s48-c-k-c0x00ffffff-no-rj"
            hover
            variant="primary"
            children="List item with an image"
          />
        </ul>
      
        <Badges rounded size="sm">sm badge</Badges>
        <hr></hr>
        <Badges rounded size="lg" variant="info">lg badge</Badges>
      </main>
    </Layout>
  );
};

export default Home;
